spring:
  session:
    store-type: mongodb
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      uri: mongodb://localhost:27017/factory-users
      database: users
server:
  port: 8080